name: Slash-commands
on:
  issue_comment:
    types: [created]
jobs:
  slash-command:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: peter-evans/slash-command-dispatch@v2
      with:
        token: ${{secrets.ADMIN_ACCESS_TOKEN}}
        issue-type: pull-request
        commands: |
          publish